version: "3.8"

x-service_defaults: &django_default
  env_file: ./config/.env
  image: ngrtec/comitari:0.2.5
  restart: "unless-stopped"
  volumes:
    - ./backend/backends:/app/backends
    - ./backend/comitari:/app/comitari
    - ./backend/core:/app/core
    - ./backend/chat:/app/chat
    - ./backend/static:/app/static
    - ./backend/users:/app/users
    - ./backend/conftest.py:/app/conftest.py
    - ./backend/manage.py:/app/manage.py
    - ./backend/pyproject.toml:/app/pyproject.toml
    - ./backend/README.md:/app/README.md
  networks:
    - comitari-network

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - comitari-network
    env_file: ./config/.env

  redis:
    image: redis:7-alpine
    container_name: redis-container
    volumes:
      - redis-data:/data
    networks:
      - comitari-network

  api:
    <<: *django_default
    container_name: api
    stop_grace_period: "5s"
    environment:
      COMMAND: development
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

networks:
  comitari-network:

volumes:
  postgres-data:
  redis-data:
