name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-backend-image:
    name: Push Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build and push"
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/django/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ghcr.io/yurinogueira/chat-django:latest

  push-frontend-image:
    name: "Push Frontend Docker Image"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
      -
        name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build and push"
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/angular/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ghcr.io/yurinogueira/chat-angular:latest
